openapi: 3.0.0
info:
  version: '0.1'
  title: Hello World
  description: Introducing open api 3.0.0

paths:
  /hello:
    get:
      tags:
        - hello
      operationId: src.hello.hello_world
      description: Returns hello world string
      responses:
        '200':
          description: 'Success'
  /sum/<arg1>/<arg2>:
    get:
      tags:
        - SUM
      operationId: src.sum.sum
      description: Returns the sum of two numbers
      responses:
        '200':
          description: 'Success'

  /cpu:
    get:
      tags:
        - CPU
      operationId: src.cpu.get_processor_name
      description: "Returns cpu information of the hosting server"
      produces:
        - "application/json"
      responses:
        "200":
          description: "CPU info, or add more text"
          schema:
            $ref: "#/definitions/CPU"

definitions:
  CPU:
    type: "object"
    required:
      - "model"
    properties:
      model:
        type: "string"
servers:
  - url: 'http://localhost:8000/e222'
