openapi: 3.0.0
info:
  version: '0.2'
  title: File Manager
  description: A service to manage files in a remote server.
  
servers:
  - url: 'http://localhost:8080/e222'

paths:
  /file/<filename>:
    post:
      tags:
        - Upload
      summary: Upload a file
      operationId: src.file.upload
      parameters:
        - name: filename
          in: query
          description: filename to be uploaded
          required: true
          schema:
            type: string
      responses:
        '405':
          description: Invalid input
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
    get:
      tags:
        - Download
      summary: Download a file
      operationId: src.file.download
      responses:
        '405':
          description: Invalid input
  /list:
    get:
      tags:
        - List
      operationId: src.file.list_files
      description: Returns the list of files in the server
      responses:
        '200':
          description: 'Success'
